---

# Main tasks file for mongodb-mms-automation-agent role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::mongodb-mms-automation-agent'
    - 'role::mongodb-mms-automation-agent::init'
