---

# Main tasks file for mongodb-mms-automation-agent role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::mongodb-mms-automation-agent'
    - 'role::mongodb-mms-automation-agent::init'
    - 'role::mongodb-mms-automation-agent::install'


- name: 'INSTALL | Manage package download from OPS Manager instance'
  include: "{{ role_path }}/tasks/manage_download_package_from_url.yml"
  when:
    - "{{ mongodb_mms_auto_agent_get_package_from_url }}"
    - "{{ mongodb_mms_auto_agent_install_package == True }}"
  tags:
    - 'role::mongodb-mms-automation-agent'
    - 'role::mongodb-mms-automation-agent::install'


- name: 'INSTALL | Manage installation tasks for your OS family'
  become: True
  include: "{{ role_path }}/tasks/install_{{ ansible_os_family | lower }}.yml"
  when:
    - "{{ mongodb_mms_auto_agent_install_package == True }}"
  tags:
    - 'role::mongodb-mms-automation-agent'
    - 'role::mongodb-mms-automation-agent::install'


- name: 'INSTALL | Manage data folder'
  become: True
  include: "{{ role_path }}/tasks/manage_data_folder.yml"
  when:
    - "{{ mongodb_mms_auto_agent_install_package == True }}"
  tags:
    - 'role::mongodb-mms-automation-agent'
    - 'role::mongodb-mms-automation-agent::install'


- name: 'CONFIG | Manage configuration tasks'
  become: True
  include: "{{ role_path }}/tasks/manage_configuration.yml"
  when:
    - "{{ mongodb_mms_auto_agent_install_package == True }}"
  tags:
    - 'role::mongodb-mms-automation-agent'
    - 'role::mongodb-mms-automation-agent::config'


- name: 'CONFIG | Manage services'
  become: True
  include: "{{ role_path }}/tasks/manage_services.yml"
  tags:
    - 'role::mongodb-mms-automation-agent'
    - 'role::mongodb-mms-automation-agent::config'
