---
- name: 'SERVICE | Manage systemd services'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  register: 'mongodb_mms_auto_agent_systemd_updated'
  with_items: "{{ mongodb_mms_auto_agent_service_systemd }}"
  when: is_systemd_managed_system


- name: 'SERVICE | systemd daemon-reload'
  systemd:
    name: 'systemd'
    daemon_reload: true
  when:
    - is_systemd_managed_system
    - mongodb_mms_auto_agent_systemd_updated.changed

- name: 'SERVICE | Manage services with init.d'
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  notify:
    - 'HANDLER | Restart mongodb-mms-automation-agent service'
  with_items: "{{ mongodb_mms_auto_agent_service_initd }}"
  when:
    - is_initd_managed_system

- name: 'CONFIG | AGENT SERVICES | Manage agent service state'
  service:
    name: "{{ mongodb_mms_auto_agent_service_name }}"
    state: "{{ mongodb_mms_auto_agent_service_state }}"
    enabled: "{{ mongodb_mms_auto_agent_service_enabled }}"
  notify: 'HANDLER | Restart mongodb-mms-automation-agent service'
  when:
    - mongodb_mms_auto_agent_install_package
    - is_initd_managed_system
