---

# Tasks about download package from an URL

- name: 'INSTALL | GET PACKAGE FROM URL | Get package file from OPS website via get_url module'
  get_url:
    url: "{{ mongodb_mms_auto_agent_package_url }}"
    dest: "{{ mongodb_mms_auto_agent_package_path }}"
  register: 'mongodb_mms_auto_agent_check_install_with_module'
  when: not mongodb_mms_auto_agent_force_curl_usage
