---

- name: 'CONFIG | AGENT SERVICES | Manage agent service state'
  service:
    name: "{{ mongodb_mms_auto_agent_service_name }}"
    state: "{{ mongodb_mms_auto_agent_service_state }}"
    enabled: "{{ mongodb_mms_auto_agent_service_enabled }}"
  notify: 'HANDLER | Restart mongodb-mms-automation-agent service'
  when:
    - "{{ mongodb_mms_auto_agent_install_package == True }}"


- name: 'CONFIG | HUGEPAGE SERVICE | Create service file'
  template:
    src: "{{ role_path }}/templates/services/initd_hugepage.j2"
    dest: "{{ mongodb_mms_auto_agent_base_folders_paths.initd }}/disable-transparent-hugepages"
    owner: 'root'
    group: 'root'
    mode: '0700'
  notify: 'HANDLER | Restart disable-transparent-hugepages service'
  when: "{{ mongodb_mms_auto_agent_manage_hugepage_settings }}"


- name: 'CONFIG | HUGEPAGE SERVICE | Manage service settings with Ansible != 2.2'
  service:
    name: 'disable-transparent-hugepages'
    state: 'started'
    enabled: True
  when:
    - "{{ mongodb_mms_auto_agent_manage_hugepage_settings }}"
    - "{{
          ((ansible_version.full | version_compare('2.2', '<'))
          or (ansible_version.full | version_compare('2.3', '>=')))
      }}"


- name: 'CONFIG | HUGEPAGE SERVICE | Manage service settings with Ansible == 2.2'
  service:
    name: 'disable-transparent-hugepages'
    state: 'started'
    enabled: True
    use: 'service'
  when:
    - "{{ mongodb_mms_auto_agent_manage_hugepage_settings }}"
    - "{{ ansible_version.full | version_compare('2.2', '>=') }}"
    - "{{ ansible_version.full | version_compare('2.3', '<') }}"
