---

# Handlers main file for mongodb-mms-automation-agent role

- name: 'HANDLER | Restart disable-transparent-hugepages service'
  become: True
  service:
    name: 'disable-transparent-hugepages'
    state: 'restarted'
  when:
    - "{{ mongodb_mms_auto_agent_manage_hugepage_settings }}"
    - "{{ mongodb_mms_auto_agent_service_enabled == True }}"
  tags:
    - 'role::mongodb-mms-automation-agent'
    - 'role::mongodb-mms-automation-agent::install'
    - 'role::mongodb-mms-automation-agent::config'


- name: 'HANDLER | Restart mongodb-mms-automation-agent service'
  become: True
  service:
    name: 'mongodb-mms-automation-agent'
    state: 'restarted'
  when:
    - "{{ mongodb_mms_auto_agent_service_enabled == True }}"
  tags:
    - 'role::mongodb-mms-automation-agent'
    - 'role::mongodb-mms-automation-agent::install'
    - 'role::mongodb-mms-automation-agent::config'
