---

# Handlers main file for mongodb-mms-automation-agent role

- name: 'HANDLER | Restart mongodb-mms-automation-agent service'
  become: True
  service:
    name: 'mongodb-mms-automation-agent'
    state: 'restarted'
  when:
    - mongodb_mms_auto_agent_service_enabled
  tags:
    - 'role::mongodb-mms-automation-agent'
    - 'role::mongodb-mms-automation-agent::install'
    - 'role::mongodb-mms-automation-agent::config'
